Repository BugWithHunter/MountainSpirit, pull requests merged in 2025-09, with the labels that each got.

#13 [feat] Http 기능 개발 & 공공 데이터 수집 및 DB 저장
  1_CodeSoruce/build.gradle
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/Mountain/command/controller/MountainController.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/Mountain/command/dto/ResponseApiMountainDTO.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/Mountain/command/dto/ResponseApiPeakDTO.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/Mountain/command/entity/Course.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/Mountain/command/entity/Mountain.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/Mountain/command/repository/CourseRepository.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/Mountain/command/repository/MountainRepository.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/Mountain/command/service/HttpUtil.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/Mountain/command/service/MountainService.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/Mountain/query/controller/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/Mountain/query/dto/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/Mountain/query/mapper/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/Mountain/query/service/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/common/Pagination.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/common/PagingButtonInfo.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/config/ApplConfig.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/config/HttpClientConfig.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/sampledomain/command/controller/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/sampledomain/command/dto/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/sampledomain/command/entity/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/sampledomain/command/repository/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/sampledomain/command/service/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/sampledomain/query/controller/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/sampledomain/query/dto/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/sampledomain/query/mapper/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/sampledomain/query/service/.gitkeep
  1_CodeSoruce/src/main/resources/static/.gitkeep
  1_CodeSoruce/src/main/resources/templates/.gitkeep
Labels: 산, 코스, API연동

#20 Ref/merge main to develop
  1_CodeSoruce/build.gradle
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/Mountain/command/controller/MountainController.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/Mountain/command/dto/ResponseApiMountainDTO.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/Mountain/command/dto/ResponseApiPeakDTO.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/Mountain/command/entity/Course.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/Mountain/command/entity/Mountain.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/Mountain/command/repository/CourseRepository.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/Mountain/command/repository/MountainRepository.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/Mountain/command/service/HttpUtil.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/Mountain/command/service/MountainService.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/Mountain/query/controller/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/Mountain/query/dto/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/Mountain/query/mapper/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/Mountain/query/service/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/config/ApplConfig.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/config/HttpClientConfig.java
Labels: 세팅

#23 [feat] #12 크루 관련 기능 개발
  .idea/.gitignore
  .idea/MountainSpirit.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/config/ApplConfig.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/config/MybatisConfig.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/crew/command/controller/CrewCommendController.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/crew/command/dto/CrewDeleteDTO.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/crew/command/dto/CrewModifyDTO.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/crew/command/dto/CrewRegistDTO.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/crew/command/entity/Crew.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/crew/command/repository/CrewCommendRepository.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/crew/command/service/CrewCommendService.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/crew/command/service/CrewCommendServiceInter.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/crew/query/controller/CrewQueryController.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/crew/query/dto/CrewDTO.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/crew/query/mapper/CrewMapper.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/crew/query/service/CrewQueryService.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/crew/query/service/CrewQueryServiceInter.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/member/command/controller/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/member/command/dto/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/member/command/entity/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/member/command/repository/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/member/command/service/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/member/query/controller/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/member/query/controller/Controller.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/member/query/controller/test.http
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/member/query/dto/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/member/query/mapper/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/member/query/service/.gitkeep
  1_CodeSoruce/src/main/resources/com/bughunters/mountainspirit/crew/query/mapper/CrewMapper.xml
Labels: 크루

#37 Feat/mountaincourseselect
  .gradle/8.14.3/checksums/checksums.lock
  .gradle/8.14.3/fileChanges/last-build.bin
  .gradle/8.14.3/fileHashes/fileHashes.lock
  .gradle/8.14.3/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/vcs-1/gc.properties
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountain/command/controller/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountain/command/controller/MountainController.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountain/command/dto/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountain/command/dto/CourseDTO.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountain/command/dto/MountainDTO.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountain/command/dto/ResponseApiMountainDTO.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountain/command/dto/ResponseApiPeakDTO.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountain/command/entity/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountain/command/entity/Course.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountain/command/entity/Mountain.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountain/command/repository/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountain/command/repository/CourseRepository.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountain/command/repository/MountainRepository.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountain/command/service/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountain/command/service/HttpUtil.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountain/command/service/MountainService.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountain/query/controller/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountain/query/controller/MountainController.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountain/query/controller/test.http
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountain/query/dto/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountain/query/dto/CourseDTO.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountain/query/dto/MountainDTO.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountain/query/mapper/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountain/query/mapper/CourseGetMapper.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountain/query/mapper/MountainGetMapper.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountain/query/service/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountain/query/service/MountainSearchService.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountain/query/service/MountainSearchServiceImpl.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountainreview/query/controller/MountainReviewController.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountainreview/query/dto/CourseReviewDTO.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountainreview/query/dto/MountainReviewDTO.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountainreview/query/mapper/CourseReviewGetMapper.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountainreview/query/mapper/MountainReviewGetMapper.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountainreview/query/service/MountainReviewService.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountainreview/query/service/MountainReviewServiceImpl.java
  1_CodeSoruce/src/main/resources/com/bughunters/mountainspirit/mountain/query/mapper/CourseGetMapper.xml
  1_CodeSoruce/src/main/resources/com/bughunters/mountainspirit/mountain/query/mapper/MountainGetMapper.xml
  1_CodeSoruce/src/main/resources/com/bughunters/mountainspirit/mountainreview/query/mapper/MountainReviewGetMapper.xml
Labels: 산, 코스

#45 [Feat] 등산 완료 후 점수, 등급 업데이트 기능 개발
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/climbhistory/command/dto/RequestRankDTO.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/climbhistory/command/service/ClimbHistoryServiceImpl.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/member/command/controller/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/member/command/dto/RequestModifyStatusOfMemberDTO.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/member/command/dto/ResponseStatusDTO.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/member/command/entity/Member.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/member/command/repository/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/member/command/repository/MemberRepository.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/member/command/service/MemberService.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/member/command/service/MemberServiceImpl.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/member/query/controller/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/member/query/dto/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/member/query/mapper/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/member/query/service/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/memberrank/command/controller/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/memberrank/command/dto/RequestRankDTO.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/memberrank/command/dto/ResponseMountainRankDTO.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/memberrank/command/dto/ResponseRankDTO.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/memberrank/command/entity/MemberRank.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/memberrank/command/entity/MountainRank.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/memberrank/command/entity/MountainRankStandard.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/memberrank/command/entity/ScoreStandard.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/memberrank/command/repository/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/memberrank/command/repository/MemberRankRepository.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/memberrank/command/repository/MemberRankRepositroy.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/memberrank/command/repository/MountainRankRepository.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/memberrank/command/repository/MountainRankStandardRepository.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/memberrank/command/repository/ScoreStandardRepository.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/memberrank/command/service/MemberRankService.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/memberrank/command/service/MemberRankServiceImpl.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/memberrank/query/controller/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/memberrank/query/dto/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/memberrank/query/dto/HigherClimber.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/memberrank/query/mapper/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/memberrank/query/mapper/MemberRankQueryRepository.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/memberrank/query/service/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/memberrank/query/service/MemberRankQueryService.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/memberrank/query/service/MemberRankQueryServiceImpl.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/stamp/command/dto/ResponseRankDTO.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/stamp/command/dto/StampWithCourseAndMountainDTO.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/stamp/command/repository/MountainStampRepository.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/stamp/command/service/StampServiceImpl.java
  1_CodeSoruce/src/main/resources/com/bughunters/mountainspirit/climbhistory/query/mapper/ClimbHistoryQueryRepository.xml
  1_CodeSoruce/src/main/resources/com/bughunters/mountainspirit/memberrank/query/mapper/MemberRankQueryRepository.xml
Labels: 산, 회원

#46 [feat] 산 & 코스 후기 CRUD 개발
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/MountainspiritApplication.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountain/command/repository/MountainRepository.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountain/command/service/MountainService.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountain/command/service/MountainServiceImpl.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountainreview/command/controller/MountainReviewController.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountainreview/command/dto/CourseReviewDTO.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountainreview/command/dto/MountainReviewDTO.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountainreview/command/entity/CourseReview.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountainreview/command/entity/MountainReview.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountainreview/command/repository/CourseReviewRepository.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountainreview/command/repository/MountainReviewRepository.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountainreview/command/service/MountainReviewService.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountainreview/query/controller/MountainReviewController.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountainreview/query/mapper/CourseReviewGetMapper.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountainreview/query/service/MountainReviewService.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountainreview/query/service/MountainReviewServiceImpl.java
  1_CodeSoruce/src/main/resources/com/bughunters/mountainspirit/mountainreview/query/mapper/CourseReviewGetMapper.xml
Labels: 산, 코스

#53 Feat/khg
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/member/command/controller/MemberController.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/member/command/entity/Member.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/member/command/service/MemberService.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/member/command/service/MemberServiceImpl.java
  2_DDL/BaseData.sql
  2_DDL/DDL.sql
Labels: 회원

#57 refact: #56 member service에서 crewId insert 구현
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/crewmember/command/entity/Member.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/crewmember/command/repository/MemberCommendRepository.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/crewmember/command/service/CrewMemberCommendServiceImpl.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/member/command/controller/MemberController.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/member/command/service/MemberService.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/member/command/service/MemberServiceImpl.java
Labels: 크루, 회원

#62 Feat/jgi 원격 브렌치 삭제 이후 신고작업 현진행 PR요청
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/report/command/controller/ReportCommandController.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/report/command/dto/ReportIsAccepted.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/report/command/dto/ReportRequestCommandDTO.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/report/command/dto/ReportResponseCommandDTO.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/report/command/entity/BanCommandEntity.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/report/command/entity/BlacklistCommandEntity.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/report/command/entity/ReportCategoryCommandEntity.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/report/command/entity/ReportCommandEntity.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/report/command/repository/BanCommandRepository.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/report/command/repository/BlacklistCommandRepository.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/report/command/repository/ReportCategoryCommandRepository.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/report/command/repository/ReportCommandRepository.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/report/command/repository/ReportMemberCommandRepository.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/report/command/service/ReportCommandService.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/report/command/service/ReportCommandServiceImpl.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/report/query/controller/BanQueryController.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/report/query/controller/BlacklistQueryController.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/report/query/controller/ReportQueryController.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/report/query/dto/BanQueryDTO.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/report/query/dto/BlacklistQueryDTO.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/report/query/dto/ReportQueryDTO.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/report/query/mapper/BanQueryMapper.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/report/query/mapper/BlacklistQueryMapper.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/report/query/mapper/ReportQueryMapper.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/report/query/service/BanQueryService.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/report/query/service/BanQueryServiceImpl.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/report/query/service/BlacklistQueryService.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/report/query/service/BlacklistQueryServiceImpl.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/report/query/service/ReportQueryService.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/report/query/service/ReportQueryServiceImpl.java
  1_CodeSoruce/src/main/resources/com/bughunters/mountainspirit/report/query/mapper/BanQueryMapper.xml
  1_CodeSoruce/src/main/resources/com/bughunters/mountainspirit/report/query/mapper/BlackListQueryMapper.xml
  1_CodeSoruce/src/main/resources/com/bughunters/mountainspirit/report/query/mapper/ReportQueryMapper.xml
  1_CodeSoruce/src/test/java/com/bughunters/mountainspirit/report/command/service/ReportCommandServiceImplTest.java
  1_CodeSoruce/src/test/java/com/bughunters/mountainspirit/report/query/service/BanQueryServiceImplTest.java
  1_CodeSoruce/src/test/java/com/bughunters/mountainspirit/report/query/service/BlacklistQueryServiceImplTest.java
  1_CodeSoruce/src/test/java/com/bughunters/mountainspirit/report/query/service/ReportQueryServiceImplTest.java
  3_gateway/.gradle/8.14.3/checksums/checksums.lock
  3_gateway/.gradle/8.14.3/checksums/md5-checksums.bin
  3_gateway/.gradle/8.14.3/checksums/sha1-checksums.bin
  3_gateway/.gradle/8.14.3/executionHistory/executionHistory.lock
  3_gateway/.gradle/8.14.3/fileChanges/last-build.bin
  3_gateway/.gradle/8.14.3/fileHashes/fileHashes.bin
  3_gateway/.gradle/8.14.3/fileHashes/fileHashes.lock
  3_gateway/.gradle/8.14.3/gc.properties
  3_gateway/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  3_gateway/.gradle/buildOutputCleanup/cache.properties
  3_gateway/.gradle/vcs-1/gc.properties
  3_gateway/.idea/.gitignore
  3_gateway/.idea/.name
  3_gateway/.idea/compiler.xml
  3_gateway/.idea/gradle.xml
  3_gateway/.idea/misc.xml
  3_gateway/.idea/modules.xml
  3_gateway/.idea/vcs.xml
  3_gateway/3_gateway.iml
  3_gateway/HELP.md
Labels: 신고

#71 [refact] 산&코스 조회 리팩토링
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/mountain/query/controller/MountainController.java
Labels: 산, 코스

#82 comment 기능 구현
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/common/JwtFilter.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/postcomment/command/controller/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/postcomment/command/controller/CommentController.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/postcomment/command/dto/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/postcomment/command/dto/RegistCommentDTO.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/postcomment/command/entity/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/postcomment/command/entity/Comment.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/postcomment/command/repository/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/postcomment/command/repository/CommentRepository.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/postcomment/command/service/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/postcomment/command/service/CommentService.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/postcomment/command/service/CommentServiceImpl.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/postcomment/query/controller/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/postcomment/query/controller/CommentReadController.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/postcomment/query/dto/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/postcomment/query/dto/CommentDTO.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/postcomment/query/mapper/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/postcomment/query/mapper/CommentGetMapper.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/postcomment/query/service/.gitkeep
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/postcomment/query/service/CommentReadService.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/postcomment/query/service/CommentReadServiceImpl.java
  1_CodeSoruce/src/main/resources/com/bughunters/mountainspirit/postcomment/query/mapper/CommentGetMapper.xml
Labels: 댓글

#85 feat: #84 crew openfeign 통신 구현 + gateway 클라이언트 추가
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/crewmember/command/infrastructure/MemberServiceClient.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/crewmember/command/service/CrewMemberCommendServiceImpl.java
  3_MemberCodeSoruce/src/main/java/com/bughunters/mountainspirit/member/command/controller/MemberController.java
  3_MemberCodeSoruce/src/main/java/com/bughunters/mountainspirit/member/command/service/MemberService.java
  3_MemberCodeSoruce/src/main/java/com/bughunters/mountainspirit/member/command/service/MemberServiceImpl.java
  gateway/gateway/src/main/resources/application.yml
Labels: MSA

#89 오류 수정
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/board/command/dto/ResponseRegistPostDTO.java
  1_CodeSoruce/src/main/java/com/bughunters/mountainspirit/board/command/service/BoardServiceImpl.java
Labels: 게시글
